version: "1.0"
info:
  model: int-scaffold
packages:
- name: ShshiOriginExternalProject
  gitServerName: shilpa
  gitUrl: https://github.com/Shilpa-Shivaji-IBM
  gitUsername: Shilpa-Shivaji-IBM
  gitBranch: main
